/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIdRouteRouteImport } from './routes/app/$appId/route'
import { Route as AppAppIdIndexRouteImport } from './routes/app/$appId/index'
import { Route as AppAppIdConfigRouteImport } from './routes/app/$appId/config'
import { Route as AppAppIdDataDatabaseTableRouteImport } from './routes/app/$appId/data/$database.$table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdRouteRoute = AppAppIdRouteRouteImport.update({
  id: '/app/$appId',
  path: '/app/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdIndexRoute = AppAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppIdRouteRoute,
} as any)
const AppAppIdConfigRoute = AppAppIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppAppIdRouteRoute,
} as any)
const AppAppIdDataDatabaseTableRoute =
  AppAppIdDataDatabaseTableRouteImport.update({
    id: '/data/$database/$table',
    path: '/data/$database/$table',
    getParentRoute: () => AppAppIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$appId': typeof AppAppIdRouteRouteWithChildren
  '/app/$appId/config': typeof AppAppIdConfigRoute
  '/app/$appId/': typeof AppAppIdIndexRoute
  '/app/$appId/data/$database/$table': typeof AppAppIdDataDatabaseTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$appId/config': typeof AppAppIdConfigRoute
  '/app/$appId': typeof AppAppIdIndexRoute
  '/app/$appId/data/$database/$table': typeof AppAppIdDataDatabaseTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/$appId': typeof AppAppIdRouteRouteWithChildren
  '/app/$appId/config': typeof AppAppIdConfigRoute
  '/app/$appId/': typeof AppAppIdIndexRoute
  '/app/$appId/data/$database/$table': typeof AppAppIdDataDatabaseTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$appId'
    | '/app/$appId/config'
    | '/app/$appId/'
    | '/app/$appId/data/$database/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$appId/config'
    | '/app/$appId'
    | '/app/$appId/data/$database/$table'
  id:
    | '__root__'
    | '/'
    | '/app/$appId'
    | '/app/$appId/config'
    | '/app/$appId/'
    | '/app/$appId/data/$database/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAppIdRouteRoute: typeof AppAppIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId': {
      id: '/app/$appId'
      path: '/app/$appId'
      fullPath: '/app/$appId'
      preLoaderRoute: typeof AppAppIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId/': {
      id: '/app/$appId/'
      path: '/'
      fullPath: '/app/$appId/'
      preLoaderRoute: typeof AppAppIdIndexRouteImport
      parentRoute: typeof AppAppIdRouteRoute
    }
    '/app/$appId/config': {
      id: '/app/$appId/config'
      path: '/config'
      fullPath: '/app/$appId/config'
      preLoaderRoute: typeof AppAppIdConfigRouteImport
      parentRoute: typeof AppAppIdRouteRoute
    }
    '/app/$appId/data/$database/$table': {
      id: '/app/$appId/data/$database/$table'
      path: '/data/$database/$table'
      fullPath: '/app/$appId/data/$database/$table'
      preLoaderRoute: typeof AppAppIdDataDatabaseTableRouteImport
      parentRoute: typeof AppAppIdRouteRoute
    }
  }
}

interface AppAppIdRouteRouteChildren {
  AppAppIdConfigRoute: typeof AppAppIdConfigRoute
  AppAppIdIndexRoute: typeof AppAppIdIndexRoute
  AppAppIdDataDatabaseTableRoute: typeof AppAppIdDataDatabaseTableRoute
}

const AppAppIdRouteRouteChildren: AppAppIdRouteRouteChildren = {
  AppAppIdConfigRoute: AppAppIdConfigRoute,
  AppAppIdIndexRoute: AppAppIdIndexRoute,
  AppAppIdDataDatabaseTableRoute: AppAppIdDataDatabaseTableRoute,
}

const AppAppIdRouteRouteWithChildren = AppAppIdRouteRoute._addFileChildren(
  AppAppIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAppIdRouteRoute: AppAppIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
